version: 0.2

env:
  parameter-store:
    Password: "ViiteUserPassword"
    Username: "ViiteUserName"


phases:
  build:
    commands:
      - echo Selecting browser based on weekday
      - if [ $( date '+%u' ) -le 5 ]; then SELAIN=chromium; else SELAIN=firefox;  fi
      - echo Selected Browser=$SELAIN
      - robot -d /robotlogs -T -v LiviUSER:$Username -v LiviPWD:$Password -v BROWSER:$SELAIN -v HEADLESS="True" Robot-Tests/

 artifacts:
  files:
    - '/robotlogs/*'
  name: $(date +%Y-%m-%d)-$SELAIN